/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AnswerQuestRequest {
    'questionDescription'?: string;
    'answer'?: string;
}
export interface ApiResponseBodyDataListQuestDTO {
    'data'?: DataListQuestDTO;
    'message'?: string;
    'statusCode'?: number;
}
export interface ApiResponseBodyGradingResult {
    'data'?: GradingResult;
    'message'?: string;
    'statusCode'?: number;
}
export interface DataListQuestDTO {
    'total'?: number;
    'data'?: Array<QuestDTO>;
    'page'?: number;
    'size'?: number;
}
export interface GetQuestListRequest {
    'query'?: string;
    'type'?: string;
    'page'?: number;
    'size'?: number;
}
export interface GradingResult {
    'isCorrect'?: boolean;
    'score'?: number;
    'feedback'?: string;
    'improvementHint'?: string;
}
export interface QuestDTO {
    'id'?: string;
    'title'?: string;
    'description'?: string;
    'type'?: QuestDTOTypeEnum;
    'actionType'?: QuestDTOActionTypeEnum;
    'answerHint'?: string;
}

export const QuestDTOTypeEnum = {
    Knowledge: 'KNOWLEDGE'
} as const;

export type QuestDTOTypeEnum = typeof QuestDTOTypeEnum[keyof typeof QuestDTOTypeEnum];
export const QuestDTOActionTypeEnum = {
    InputText: 'input_text'
} as const;

export type QuestDTOActionTypeEnum = typeof QuestDTOActionTypeEnum[keyof typeof QuestDTOActionTypeEnum];


/**
 * QuestControllerApi - axios parameter creator
 */
export const QuestControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Answer Quest
         * @param {string} questId 
         * @param {AnswerQuestRequest} answerQuestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        answerQuest: async (questId: string, answerQuestRequest: AnswerQuestRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questId' is not null or undefined
            assertParamExists('answerQuest', 'questId', questId)
            // verify required parameter 'answerQuestRequest' is not null or undefined
            assertParamExists('answerQuest', 'answerQuestRequest', answerQuestRequest)
            const localVarPath = `/api/v1/quest/{questId}/answer`
                .replace(`{${"questId"}}`, encodeURIComponent(String(questId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(answerQuestRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Quest List
         * @param {GetQuestListRequest} getQuestListRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestList: async (getQuestListRequest: GetQuestListRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'getQuestListRequest' is not null or undefined
            assertParamExists('getQuestList', 'getQuestListRequest', getQuestListRequest)
            const localVarPath = `/api/v1/quest/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(getQuestListRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuestControllerApi - functional programming interface
 */
export const QuestControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QuestControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Answer Quest
         * @param {string} questId 
         * @param {AnswerQuestRequest} answerQuestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async answerQuest(questId: string, answerQuestRequest: AnswerQuestRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseBodyGradingResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.answerQuest(questId, answerQuestRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestControllerApi.answerQuest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Quest List
         * @param {GetQuestListRequest} getQuestListRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestList(getQuestListRequest: GetQuestListRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseBodyDataListQuestDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestList(getQuestListRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestControllerApi.getQuestList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QuestControllerApi - factory interface
 */
export const QuestControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QuestControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary Answer Quest
         * @param {string} questId 
         * @param {AnswerQuestRequest} answerQuestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        answerQuest(questId: string, answerQuestRequest: AnswerQuestRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseBodyGradingResult> {
            return localVarFp.answerQuest(questId, answerQuestRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Quest List
         * @param {GetQuestListRequest} getQuestListRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestList(getQuestListRequest: GetQuestListRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseBodyDataListQuestDTO> {
            return localVarFp.getQuestList(getQuestListRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QuestControllerApi - object-oriented interface
 */
export class QuestControllerApi extends BaseAPI {
    /**
     * 
     * @summary Answer Quest
     * @param {string} questId 
     * @param {AnswerQuestRequest} answerQuestRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public answerQuest(questId: string, answerQuestRequest: AnswerQuestRequest, options?: RawAxiosRequestConfig) {
        return QuestControllerApiFp(this.configuration).answerQuest(questId, answerQuestRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Quest List
     * @param {GetQuestListRequest} getQuestListRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQuestList(getQuestListRequest: GetQuestListRequest, options?: RawAxiosRequestConfig) {
        return QuestControllerApiFp(this.configuration).getQuestList(getQuestListRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



